# see http://docs.travis-ci.com/user/languages/java/
language: java
jdk:
  - oraclejdk8

# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# see http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

# see http://docs.travis-ci.com/user/notifications/
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/42cb2115cb4f693ebe05
    on_success: always  # options: [always|never|change]
    on_failure: always  # options: [always|never|change]
    on_start: false     # default: false
  slack:
    secure: DaKXzJPZzi2/mkCtJRLVkJ+UYO7+tA2afQ0aDrG91xK5uHFyWCtstdVe+4/F00WamtHnuc+pFNRP2YQywFknd0KaR57Ny2/Thd55qfkoOa6s9INp4ZJUzRTe5hMhrzn/mmW2khmWwRlPaqXif0F3qS+xTxULM4Ys14RCd5ESGIE=
